// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entityCodeFirst.Data;

namespace entityCodeFirst.Migrations.ClasseDb
{
    [DbContext(typeof(ClasseDbContext))]
    [Migration("20220527080124_AddClasse4")]
    partial class AddClasse4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("entityCodeFirst.Models.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Departement")
                        .HasColumnType("text");

                    b.Property<string>("NameClasse")
                        .HasColumnType("text");

                    b.HasKey("IdClasse");

                    b.ToTable("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
